version: '3'
services: 
    anaconda:
        build: .
        volumes:
            - '.:/opt/100knock-process-visualization'
        ports:
            - '8888:8888'
        tty: true
        platform: linux/amd64